### ISSUE TITLE
I'm having problems setting up

### ISSUE THREAD

**Issue by NancyMoo** [petkivim/embed-google-map#26]
Hi
I've just installed and enabled the plugin.
However I can't get it to work... I've tried various variations of the string, that I'm typing into a module.
{google_map}55.369157,-3.9989294,12{/google_map}
{google_map}Glasgow Road Sanquhar Dumfriesshire DG4 6BZ{/google_map}
{google_map}Glasgow Road Sanquhar{/google_map}

None of which are working at all. My Joomla site is running on Php5.6
Do you have any ideas what I'm doing wrong please?

Thanks

**Comment by petkivim** [comment]
Hi,

Could you please provide some further information about the problem? Do you get an error message or are you seeing the ```{google_map}....{/google_map}``` code instead of the map? If you're seeing the code you should check that

1. The plugin is enabled: 
  * Extensions -> Plugins -> Embed Google Map -> Status -> Enabled
2. Prepare content is set to ```Yes``` if you're using a custom HTML module: 
  * Extensions -> Modules -> Your Module -> Options -> Prepare Content -> Yes

Br,
Petteri

**Comment by NancyMoo** [comment]
Hello

Thank you VERY much for your reply... it was the 'Prepare Content' option
that wasn't enabled on my module.

Have an excellent rest of the day and thanks again

Jeanette
