### ISSUE TITLE
New embed api

### ISSUE THREAD

**Issue by yozmag** [petkivim/embed-google-map#64]
I have tried to allow this plugin to work with the google https://developers.google.com/maps/documentation/embed/guide api.
Created a new EmbedGoogleMapNewV2HtmlBuilder class with this option.
If you could review this addition and incorporated with your code would be great,
Thank you for your work.
[embed_google_map2.2.0.zip](https://github.com/petkivim/embed-google-map/files/2850796/embed_google_map2.2.0.zip)

**Comment by petkivim** [comment]
Thank you for your contribution! Your implementation adds support to Google Maps embed API that is already supported by Embed Google Maps plugin (`version:embed`). However, there was a problem with the implementation that is fixed in version [2.1.1](https://github.com/petkivim/embed-google-map/releases/tag/v2.1.1). 

Regards,
Petteri
