### ISSUE TITLE
Embed in module?

### ISSUE THREAD

**Issue by annettenugent** [petkivim/embed-google-map#9]
Hi.

I want to include a google map within a module thats already created.

The editor is in developer mode.
What is the correct line of code I should include?

<section class="map-section">
	<header class="heading">
		<h1>FIND US HERE...</h1>
	</header>
	<{google_map}https://goo.gl/maps/w6bFf{/google_map}>
</section>

**Comment by petkivim** [comment]
Hi,

First you should check that your module's ```Prepare Content``` setting is set to ```Yes```. You can find it under the Options tab in the module's settings.

After updating the setting the code below should do the job. Unfortunately you have to use the full URL, because the plugin doesn't support shortened URLs currently.

```
{google_map}https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d73483.11156689911!2d-6.3973560282765325!3d54.86171363380064!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x48604cf52770a9e7%3A0xe723adee56681d1!2sTotal+Pools+%26+Leisure%2C+62+Fenaghy+Road%2C+Galgorm+Industrial+Estate%2C+Ballymena%2C+Antrim+BT42+1FL%2C+United+Kingdom!3m2!1d54.861733!2d-6.32869!5e0!3m2!1sen!2suk!4v1439142569472{/google_map}
```

Best regards,
Petteri
