### ISSUE TITLE
Place marker not showing, but is visible on Google Maps site

### ISSUE THREAD

**Issue by DaveMoss69** [petkivim/embed-google-map#91]
My place is available on Google maps but the embedded plugin doesn't show it. This is the address embedded in a text article.
Unit 20 Grange Farm Industrial Estate Little Chesterton Bicester OX25 3PD
Snapshot from Google maps attached, as you can see it shows on here.
Any help is appreciated. Thanks.
<img width="842" alt="Screenshot 2024-04-24 at 07 24 26" src="https://github.com/petkivim/embed-google-map/assets/10495850/783eac9c-a25a-4f8f-8742-c844ccb30756">

**Comment by petkivim** [comment]
Hi @DaveMoss69! Unfortunately, I'm not able to show the location using the plugin either.  I'd guess that it's because the address (`Unit 20, Grange Farm Industrial Estate, Little Chesterton, Bicester OX25 3PD, United Kingdom`) returns multiple search results on Google Maps. However, there's a workaround to the issue.

In addition to embedding maps with an address, it's possible to embed maps created in Google Maps using the map URL. You could create a map with your location and then embed it using the plugin. This is how it could look like (the icon and its color are configurable):

```
{google_map}https://www.google.com/maps/d/view?mid=1myVXji6is2k4YquD7d4PSECPRoq5Hws&usp=sharing{/google_map}
```

<img width="346" alt="Screenshot 2024-04-28 at 13 39 16" src="https://github.com/petkivim/embed-google-map/assets/575897/762e8c97-73cd-4aab-bdb8-dc6a44059750">

Before embedding a map please make sure that the map is public and can be viewed by anyone. Please see how to [share your map](https://support.google.com/mymaps/answer/3024935?hl=en&ref_topic=3526007).

**Comment by DaveMoss69** [comment]
Thank you for taking the time to reply. It's appreciated.
Dave
